# Site Information
authors: Jeremy Wong
name: Continued Learning
description: website to continue learning

# Build Settings
markdown: redcarpet
permalink: /:title/
exclude: [
  'node_modules',
  'package.json',
  'README.md',
  'book_notes',
  'topics',
  'LICENSE',
  'Rakefile',
]
timezone: UTC
encoding: utf-8
baseurl: "/continued-learning" # the subpath of the website
url: http://127.0.0.1:4000
gems: []
sass:
  sass_dir: _sass
  style: compressed
